[main]
font=RobotoMono Nerd Font:size=13
prompt=❯ 
terminal=foot
[colors]
background=05050fee
text=00ffccff
match=ff00ffff
selection=00ffff22
selection-text=00ffff ff
border=00ffff ff
[border]
width=2
radius=0
[dmenu]
# if using as dmenu replacement
exit-immediately-if-empty=true
