[warning]
font=RobotoMono Nerd Font Bold 13
background=00FFFF
text=0A0A0F
border=00FFFF
button-background=000000
button-text=00FFFF
button-border=00FFFF
border-bottom=00FF00
border-bottom-size=8
[error]
font=RobotoMono Nerd Font Bold 13
background=FF00FF
text=0A0A0F
border=FF00FF
button-background=000000
button-text=FF00FF
button-border=FF00FF
border-bottom=00FF00
border-bottom-size=8
